// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQn0VmNDLSDmEaqtK7wl1gF36erFYVmpg',
    appId: '1:676706330164:web:cd620dfd80d87a8e704c61',
    messagingSenderId: '676706330164',
    projectId: 'user-app-robby',
    authDomain: 'user-app-robby.firebaseapp.com',
    databaseURL: 'https://user-app-robby-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'user-app-robby.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEzJlcyIOaH8FglFzzstmddx-d4K9_BE',
    appId: '1:676706330164:android:2533323144ad7165704c61',
    messagingSenderId: '676706330164',
    projectId: 'user-app-robby',
    databaseURL: 'https://user-app-robby-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'user-app-robby.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChdyaL2K5H1n8Ya-Pj9lF5LWVTe4XY4Pg',
    appId: '1:676706330164:ios:254a45ac0bfd4c1e704c61',
    messagingSenderId: '676706330164',
    projectId: 'user-app-robby',
    databaseURL: 'https://user-app-robby-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'user-app-robby.appspot.com',
    iosBundleId: 'com.nyimpang.nyimpangCooperative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChdyaL2K5H1n8Ya-Pj9lF5LWVTe4XY4Pg',
    appId: '1:676706330164:ios:5dba41aafdf91fe9704c61',
    messagingSenderId: '676706330164',
    projectId: 'user-app-robby',
    databaseURL: 'https://user-app-robby-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'user-app-robby.appspot.com',
    iosBundleId: 'com.nyimpang.nyimpangCooperative.RunnerTests',
  );
}
