// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YFNS3RNxAmzPN4ZYbyK2F3Eu9st0ras',
    appId: '1:833957584926:web:53de7cab6d6fdda8408e0f',
    messagingSenderId: '833957584926',
    projectId: 'nyimpang-cooperative',
    authDomain: 'nyimpang-cooperative.firebaseapp.com',
    storageBucket: 'nyimpang-cooperative.appspot.com',
    measurementId: 'G-1K0E0QL30G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEPv6acq9NCEJF0F7W22eqnsQywIP1m0',
    appId: '1:833957584926:android:06f7a85d3622b4a3408e0f',
    messagingSenderId: '833957584926',
    projectId: 'nyimpang-cooperative',
    storageBucket: 'nyimpang-cooperative.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApER2wlTI5ZeluFxuBQ3W8uVcL4LENXmw',
    appId: '1:833957584926:ios:4d39144dee039f60408e0f',
    messagingSenderId: '833957584926',
    projectId: 'nyimpang-cooperative',
    storageBucket: 'nyimpang-cooperative.appspot.com',
    iosBundleId: 'com.nyimpang.nyimpangCooperative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApER2wlTI5ZeluFxuBQ3W8uVcL4LENXmw',
    appId: '1:833957584926:ios:54e13992a2bb4297408e0f',
    messagingSenderId: '833957584926',
    projectId: 'nyimpang-cooperative',
    storageBucket: 'nyimpang-cooperative.appspot.com',
    iosBundleId: 'com.nyimpang.nyimpangCooperative.RunnerTests',
  );
}
